### PR TITLE
ECMAScript Modules and Client Isolation

### PR DESCRIPTION
**Pull request by rafaelvieiras**
### Creating a database middleware.
For now, we use **diskdb** to save information, but, on future we may want to add new ways to save information, an **SQL**, plain **json** or simple change diskdb to **another lib**. Thinking on this, I'm created a **Database** class, to manager save, update, list and find. Without the other codes knowing which lib being in use.

### Driver Class & Driver Router
The concept behind The **Driver** is to manager information to client with multiple media-server, or any media-server type, like Emby, **Plex** or Jellyfin, without exclusivity.

The Driver can add media service on PseudoTv server without an exclusive service type.
The Driver possibility the channel end-point return a channel with multiple media sources or just without an exclusive service.

### ECMAScript Modules
Changed from `require` to `import`.
All modules are now exported by `export` and no more by `module.export`. 

Related with #20 and #19

### CODE REVIEW

**Comment by rafaelvieiras** [comment]
@DEFENDORe and @powdermilkman, I'm very anxious for your opinion. Remember, this PR is Work in Progress.

**Comment by powdermilkman** [comment]
@rafaelvieiras if you're interested you should take a look at the rebuild branch, we are looking to rebuild the app in vue.js. Join us on the discord https://discord.gg/PCZYH6

**Comment by rafaelvieiras** [comment]
@powdermilkman this invite is invalid! You can add me!? rafaelvieiras#0729

**Comment by powdermilkman** [comment]
sent a friend request

**Pull request closed without merging**
